### PR TITLE
Fix: use action label instead of description in Steward cards

### PR DESCRIPTION
**Pull request by krisbitney**
Related: https://github.com/GoodDollar/GoodCollective/issues/130

### CODE REVIEW

**Comment by decentralauren** [comment]
@krisbitney to confirm:

- If the contract HAS a value, that value will display (e.g. "Stewards are paid G$ each time they measure a tree's status"
- If the contract DOES NOT HAVE a value, the default text will display: "Please see the smart contract for information regarding payment logic." ([per this ticket](https://github.com/GoodDollar/GoodCollective/issues/78#issuecomment-1916090862))

My understanding is that the Silvi contract does have this value, though I am not sure if any of the others displaying DO NOT in order for us to effectively test. 


cc @L03TJ3 @patpedrosa @vldkhh to restest once redeployed!

**Comment by krisbitney** [comment]
> @krisbitney to confirm:
> 
> * If the contract HAS a value, that value will display (e.g. "Stewards are paid G$ each time they measure a tree's status"
> * If the contract DOES NOT HAVE a value, the default text will display: "Please see the smart contract for information regarding payment logic." ([per this ticket](https://github.com/GoodDollar/GoodCollective/issues/78#issuecomment-1916090862))
> 
> My understanding is that the Silvi contract does have this value, though I am not sure if any of the others displaying DO NOT in order for us to effectively test.
> 
> cc @L03TJ3 @patpedrosa @vldkhh to restest once redeployed!

I added the property to the subgraph and named it `infoLabel`, but none of the collectives had it in their IPFS data. 

See: https://github.com/GoodDollar/GoodCollective/issues/78#issuecomment-1888710889

Unless the IPFS data has changed, I don't think that value was present for any of the collectives

**Comment by decentralauren** [comment]
@krisbitney thank you!

@L03TJ3 @sirpy should add to our to-dos to update IPFS in this case. Who should take this on?

**Comment by L03TJ3** [comment]
@decentralauren whoever created the pool will be responsible one for keeping the pool attributes updates because the owner/creator of the pool is the only one able to update the contract to new data on ipfs

**Comment by L03TJ3** [comment]
Confirmed this works, added infoLabel to new pool created
image

**Pull request merged**
