### PR TITLE
Fix: transaction list donation flowing balances showing correct amounts

### PR DESCRIPTION
**Pull request by krisbitney**
The list was previously showing the total donated by the supporter

### CODE REVIEW

**Comment by sirpy** [comment]
Lets wait for #167  decision

**Comment by L03TJ3** [comment]
@sirpy decision is made and it requested is to show the original set rate per / x
also an additional request to define the cancel stream (deleteFlow) tx as separate item/type.
Should this be done in new PR?

**Comment by krisbitney** [comment]
> @sirpy decision is made and it requested is to show the original set rate per / x also an additional request to define the cancel stream (deleteFlow) tx as separate item/type. Should this be done in new PR?

Showing the original set rate per x will require changes to the smart contracts and subsequent changes to the Subgraph

**Comment by sirpy** [comment]
I'll take over this issue
@krisbitney

**Pull request closed without merging**
